config/routes.rb
Rails.application.routes.draw do
  resources :accounts

  root 'dashboard#index'
  post 'vk_auth' => 'dashboard#vk_authorize', as: :vk_auth
  resources :accounts
  resources :messages do
    post 'status', as: :status
  end
  resources :users, only: [:index, :create, :destroy]
  get 'redirect' => 'users#redirect'
  get 'users/start_sending' => 'users#start_sending', as: :users_start_send
  mount Browserlog::Engine => '/logs', as: :logs

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @accounts = Account.all
    @messages = Message.all
    @activate = VkontakteApi.authorization_url(type: :client, scope: [:friends, :messages, :wall, :offline])
  end

  def vk_authorize
    begin
      account = Account.find(vk_params[:user_id])
      uri = URI.parse(vk_params[:user_url])
      cgi = CGI::parse(uri.fragment)

      if account.update(access_token: cgi['access_token'][0], uid: cgi['user_id'][0])
        redirect_to root_path, notice: 'Account successfully activated!'
      else
        redirect_to root_path, alert: 'Something went wrong... try to find out what in the log file'
      end
    rescue
      redirect_to root_path, alert: 'You passed not all needed parametrs. Please, try again and do it gentle)'
    end
  end

  private
  def vk_params
    params.permit(:user_id, :user_url)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.haml
.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          Accounts
          %button.btn.btn-primary.btn-xs.pull-right{"data-target" => ".bs-example-modal-sm", "data-toggle" => "modal", :type => "button"} Add new user
      .panel-body
        %table.table.table-hover
          %thead
            %tr
              %th Email
              %th Status
              %th
              %th

          %tbody
            - @accounts.each do |account|
              %tr
                %td= link_to account.email, account
                %td
                  %btn.btn.btn-xs.disabled.center-block{:class => "btn-#{add_status(account.status)}"}= account.status ? account.status : 'Unseted'
                  - if account.status.try(:to_sym) == :unactive
                    %a{:href => '#', :class=> 'btn btn-default btn-xs center-block', "data-target" => ".bs-modal-vk-auth", "data-toggle" => "modal", :target => '_blank'} Authenticate
                %td= link_to 'Edit', edit_account_path(account), :class => 'btn btn-default btn-sm'
                %td= link_to 'Destroy', account, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger btn-sm'

  .col-md-6
    .panel.panel-default.message-off
      .panel-heading
        %h3.panel-title
          %a{"aria-controls" => "collapseTable", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#collapseTable"}
            %span.glyphicon.glyphicon-menu-down{"aria-hidden" => "true"}
            Messages
          %button.btn.btn-primary.btn-xs.pull-right{"data-target" => ".bs-example-modal-sm_message", "data-toggle" => "modal", :type => "button"} Add new message
      .panel-body
        %table.table.table-hover
          %thead
            %tr
              %th Message
              %th Attachment
              %th
              %th
              %th

          %tbody
            - @messages.each do |message|
              %tr
                %td= link_to truncate(message.body, :length => 20), message
                %td
                  - if message.img_urls
                    - message.img_urls.each do |p|
                      %img{ :src => "#{p}", :width => 100, :class => 'img-thumbnail'}
                %td
                  - if message.status.to_sym == :active
                    =link_to 'Deactivate', message_status_path(message), :method => :post, :class => 'btn btn-sm btn-warning'
                  - else
                    =link_to 'Activate', message_status_path(message), :method => :post, :class => 'btn btn-sm btn-success'
                %td= link_to 'Edit', edit_message_path(message), :class => 'btn btn-default btn-sm'
                %td= link_to 'Destroy', message, :method => :delete, :class => 'btn btn-danger btn-sm'


    .panel.panel-default.collapse#collapseTable.message-on
      .panel-heading
        %h3.panel-title
          %a{"aria-controls" => "collapseTable", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#collapseTable"}
            %span.glyphicon.glyphicon-menu-up{"aria-hidden" => "true"}
            Messages
          %button.btn.btn-primary.btn-xs.pull-right{"data-target" => ".bs-example-modal-sm_message", "data-toggle" => "modal", :type => "button"} Add new message
      .panel-body
        %table.table.table-hover
          %thead
            %tr
              %th Message
              %th Attachment
              %th url
              %th Status
              %th
              %th
              %th

          %tbody
            - @messages.each do |message|
              %tr
                %td.message-body= link_to message.body, message
                %td
                  - if message.img_urls
                    - message.img_urls.each do |p|
                      %img{ :src => "#{p}", :width => 100, :class => 'img-thumbnail'}
                %th= message.url
                %th= message.status
                %td
                  - if message.status.to_sym == :active
                    =link_to 'Deactivate', message_status_path(message), :method => :post, :class => 'btn btn-sm btn-warning'
                  - else
                    =link_to 'Activate', message_status_path(message), :method => :post, :class => 'btn btn-sm btn-success'
                %td= link_to 'Edit', edit_message_path(message), :class => 'btn btn-default btn-sm'
                %td= link_to 'Destroy', message, :method => :delete, :class => 'btn btn-danger btn-sm'






.modal.fade.bs-modal-vk-auth{"aria-hidden" => "true", "aria-labelledby" => "mySmallModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-md
    .modal-header
      %a{:href => "#{@activate}", :target => '_blank', :class => 'btn btn-xs btn-primary center-block'} Click here to get url
    .modal-content
      = form_tag('/vk_auth', method: 'post', class: 'form-horizontal') do
        .form-group
          %label.col-sm-3.control-label User
          .col-sm-9
            = select_tag(:user_id, options_for_select(@accounts.collect {|p| [ p.email, p.id ] unless p.status.to_sym == :active }), class: 'form-control')
        .form-group
          %label.col-sm-3.control-label Url
          .col-sm-9
            = text_field_tag(:user_url, nil, class: 'form-control')
        .form-group
          .col-sm-offset-3.col-sm-9
            %button.btn.btn-success{:type => "submit"} Activate

.modal.fade.bs-example-modal-sm{"aria-hidden" => "true", "aria-labelledby" => "mySmallModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-sm
    .modal-content= render 'accounts/form'

.modal.fade.bs-example-modal-sm_message{"aria-hidden" => "true", "aria-labelledby" => "mySmallModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-md
    .modal-content= render 'messages/form'