config/routes.rb
Rails.application.routes.draw do
  resources :accounts

  root 'dashboard#index'
  post 'vk_auth' => 'dashboard#vk_authorize', as: :vk_auth
  resources :accounts
  resources :messages do
    post 'status', as: :status
  end
  resources :users, only: [:index, :create, :destroy]
  get 'redirect' => 'users#redirect'
  get 'users/start_sending' => 'users#start_sending', as: :users_start_send
  mount Browserlog::Engine => '/logs', as: :logs

end

app/models/user.rb
class User < ActiveRecord::Base
  include AASM
  default_scope -> {order('id')}

  serialize :messages, Hash

  enum status: [:in_line, :sended, :delivered, :failed]
  validates :url, presence: true
  before_destroy :check_status

  aasm column: :status, whiny_transitions: false, no_direct_assignment: true do
    state :in_line, :initial => true
    state :sended
    state :delivered
    state :failed

    event :message_sended do
      transitions from: :in_line, to: :sended
    end

    event :message_delivered do
      transitions from: :sended, to: :delivered
    end

    event :message_failed do
      transitions from: :in_line, to: :failed
    end
  end


  def increment_message_relation(message)
    unless self.status == User.statuses[:delivered]
      self.message_sended!
      self.message_delivered!
    end

    if self.messages.has_key?(message.id.to_s)
      self.messages[message.id.to_s] += 1
    else
      self.messages[message.id.to_s] = 1
    end
    self.save
  end


  private

  def check_status
    unless self.status.to_sym == :in_line
      errors.add(:base, "You can't destroy user which already sended.")
      false
    end
  end
end

app/controllers/users_controller.rb
require 'configatron'

class UsersController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :authenticate, except: :redirect
  layout 'paper'

  def index
    @users = User.paginate(:page => params[:page], :per_page => 10)
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: 'User created successfully!'
    else
      redirect_to users_path, alert: 'Something went wrong...'
    end
  end

  def start_sending
    if User.any? && Account.active.any? && Message.active.any?
      configatron.aproved = true
      redirect_to users_path, notice: 'Messages sending had been started!'
    else
      redirect_to users_path, alert: "I'm not gona start sending until everything will be ready! Now you have #{User.all.count} users, #{Account.active.count} active accounts and #{Message.active.count} active messages."
    end
  end

  def redirect
    message = Message.find(SecureId.new(deliver_params[:message]).decrypt.to_i)
    User.find(SecureId.new(deliver_params[:account]).decrypt.to_i).increment_message_relation(message)

    redirect_to message.url
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      redirect_to users_path, notice: 'User successfully destroyied'
    else
      redirect_to users_path, alert: 'Something went wrong...'
    end
  end

  private
  def deliver_params
    params.permit(:account, :message)
  end

  def user_params
    params.require(:user).permit(:url)
  end

  def authenticate
    authenticate_or_request_with_http_basic('Administration') do |username, password|
      md5_of_password = Digest::MD5.hexdigest(password)
      username == ENV['AUTH_USERNAME'] && md5_of_password == ENV['AUTH_PASSWORD']
    end
  end
end

app/views/users/_form.html.haml
- @user ||= User.new

.modal-body
  = form_for @user, :html => { :class=> 'form-horizontal' } do |f|
    .form-group
      %label.col-sm-3.control-label{:for => "inputUrl"} url:
      .col-sm-9
        = f.text_field :url, :class => 'form-control'
    .form-group
      .col-sm-offset-3.col-sm-9
        %button.btn.btn-success{:type => "submit"} Submit

app/views/users/index.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          Users
          %button.btn.btn-primary.btn-xs.pull-right{"data-target" => ".bs-example-modal-md_user", "data-toggle" => "modal", :type => "button"} Add new user
          %a{:href => "#{users_start_send_path}", :class => 'btn btn-success btn-xs pull-right', :style => 'color: #fff; margin-right: 10px;'} Let's start sending messages
      .panel-body
        %table.table.table-hover
          %thead
            %tr
              %th id
              %th url
              %th status
              %th network
              %th messages
              %th

          %tbody
            - @users.each do |user|
              %tr
                %td= user.id
                %td= user.url
                %td= user.status
                %td= user.network
                %td= user.messages
                %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger btn-sm'

  .col-md-12
    = will_paginate @posts, renderer: BootstrapPagination::Rails


.modal.fade.bs-example-modal-md_user{"aria-hidden" => "true", "aria-labelledby" => "mySmallModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-md
    .modal-content= render 'form'